[package]
name = "pq2json"
version = "0.1.0"
authors = ["Evgeney Ryzhyk <evgeneyr@microsoft.com>"]
edition = "2018"

[dependencies]
clap = "2"
parquet = { git = "https://github.com/rzheka/arrow.git", branch = "dev" }
itertools = "0.8"
serde = "1"
serde_json = "1"
num-bigint = "0.2"
chrono = "0.4"
